FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy nginx config
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

# Copy frontend files
COPY frontend/templates /usr/share/nginx/html/templates
COPY frontend/static /usr/share/nginx/html/static

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]