server {
    listen 80;
    server_name localhost;

    # IMPORTANT: serve from templates folder
    root /usr/share/nginx/html/templates;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static files (CSS, JS)
    location /static/ {
        alias /usr/share/nginx/html/static/;
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }

    # Backend API
    location /api/ {
         rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend:8000;

    }
}